#!/bin/sh

# defaults
GRID_UNIT_PX=18
QTWEBKIT_DPR=2.0

# override defaults by sourcing /etc/ubuntu-touch-session.d/$device.conf
device=$(getprop ro.product.device)
[ -e /etc/ubuntu-touch-session.d/$device.conf ] && . /etc/ubuntu-touch-session.d/$device.conf

export GRID_UNIT_PX=${GRID_UNIT_PX}
export QTWEBKIT_DPR=${QTWEBKIT_DPR}

if [ "$#" -ne 0 ]; then
    $@
else
    init --user
fi
