#!/bin/bash

on_stop()
{
    echo "Stopping session..."
    kill ${DBUS_SESSION_BUS_PID}
}

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    echo "Starting session bus"
    export `dbus-launch`
    if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
        echo "Unable to start session bus"
        exit 1
    fi
fi

# Initialize shell, env, etc

export HOSTNAME=android
export SHELL=/system/bin/sh
export TERM=vt100
export ANDROID_CACHE=/cache
export LOOP_MOUNTPOINT=/mnt/obb
export ASEC_MOUNTPOINT=/mnt/asec
export ANDROID_PROPERTY_WORKSPACE=8,49152
export ANDROID_ASSETS=/system/app
export ANDROID_BOOTLOGO=1
export USER=ubuntu
export LD_LIBRARY_PATH=/opt/qt5/lib:/vendor/lib:/system/lib
export QML_IMPORT_PATH=/opt/qt5/imports
export QT_FONT_PATH=/opt/qt5/lib/fonts
export PATH=/opt/qt5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export ANDROID_DATA=/data
export QT_QPA_PLATFORM=hybris
export SHLVL=1
export HOME=/home/ubuntu
export MKSH=/system/bin/sh
export ANDROID_ROOT=/system
export EXTERNAL_STORAGE=/mnt/sdcard
export QT_PLUGIN_PATH=/opt/qt5/plugins

echo "DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}" > $HOME/.dbus-session
echo "DBUS_SESSION_BUS_PID=${DBUS_SESSION_BUS_PID}" >> $HOME/.dbus-session

env

device=`grep Hardware /proc/cpuinfo | awk '{print $3}'`

if [ "$device" == "ventana" ]; then
    services="/etc/tablet-services"
else
    services="/etc/phone-services"
fi

while read service; do
    $service &
done < "$services"

trap 'on_stop' TERM

wait
