#!/bin/sh

if [ ! -e /home/phablet/.display-mir ]; then
    # LightDM will see that we failed to start and try the next seat, which
    # should be surfaceflinger.
    exit 1
fi

# We need to grab ANDROID_ROOT from /etc/environment, because Mir uses
# it to find input configuration files and autopilot won't work without that.
. /etc/environment

exec unity-system-compositor $@
